sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t suraj1291993/docker-react-tutorial -f Dockerfile.dev

script:
  - docker run -e "CI=true" suraj1291993/docker-react-tutorial npm run test